# OUTPUT_LANG_INDEX start from 0
generator-localization-starry-trainee-user:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=13m3-zhVQjKPOOOAuII4le41newmiEnkGTFghmy5LAoU GID_ID=landing OUTPUT_FOLDER=../public/locales/en/common.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=13m3-zhVQjKPOOOAuII4le41newmiEnkGTFghmy5LAoU GID_ID=landing OUTPUT_FOLDER=../public/locales/vi/common.json